#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# every you commit something the following command will be executed
# https://typicode.github.io/husky/#/?id=create-a-hook

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
npx --no-install jest

npm run lint
npm run test