# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    # We need to specify what environment to use for environment secrets
    # https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#environment-secrets
    environment: github-pages
    env:
      # Set env variables to actions secrets
      NEXT_PUBLIC_APP_GA_ID: ${{secrets.NEXT_PUBLIC_APP_GA_ID}}
      NEXT_PUBLIC_APP_GAD: ${{secrets.NEXT_PUBLIC_APP_GAD}}
      NEXT_PUBLIC_APP_GAD_ID: ${{secrets.NEXT_PUBLIC_APP_GAD_ID}}
      NEXT_PUBLIC_APP_SITE_URL: ${{secrets.NEXT_PUBLIC_APP_SITE_URL}}
      NEXT_PUBLIC_APP_VERSION: ${{secrets.NEXT_PUBLIC_APP_VERSION}}

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'yarn'

      - name: Install packages
        run: npm run install

      - name: Build the project
        run: npm build

      - name: Run unit tests
        run: npm test

      # - name: Run Cypress e2e test
      #   uses: cypress-io/github-action@v2
      #   with:
      #     start: yarn start

      - name: Build the website
        run: npm run export && touch ./out/.nojekyll
        # This below is used to build storybook static site with whole site together
        # run: npm run export-with-storybook && touch ./out/.nojekyll

      - name: Deploy webpages to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: out # The folder the action should deploy.

